name: My First Workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v4
            - name: List and read files
              run: | 
                 echo "Hello world!!"
                 ls -lrta
                 cat dragon.txt
            - name: generate ASCII artwork
              run: cowsay -f dragon "Run for Cover, I am a dragon RAAAWWWWRRRRRR ...." >> dragon.txt