name: Ascii workflow

on: push

jobs:
    ascii_art:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v4
            - name: List the files
              run: ls -lrta
            - name: Executing shell script
              run: |
                chmod +x ascii-script.sh 
                ./ascii-script.sh

                 
            
            