name: Multijob workflow

on: push

jobs:
    build_job1:
        runs-on: ubuntu-latest
        steps:
            - name: Install cowsay package
              run: sudo apt-get install cowsay -y

            - name: Execute the cowsay command
              run: cowsay -f dragon "Run for cover, I am a Dragon .... RAAWWWWRRRRRR" >> dragon.txt

            - name: sleep for 10 seconds
              run: sleep 10 
                
                
    
    test_job2:
        needs: build_job1
        runs-on: ubuntu-latest
        steps:
            - name: Search for dragon
              run: grep -i "dragon" dragon.txt
    
    
    deploy_job3:
        needs: test_job2
        runs-on: ubuntu-latest
        steps:
            - name: List the files
              run: ls -lrta

            - name: display the contents of file
              run: cat dragon.txt
                 
            
            